apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecastapp
  labels:
    app: forecastapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: forecastapp
  template:
    metadata:
      labels:
        app: forecastapp
    spec:
      containers:
        - image: oraharon/kube-jenkins-docker:54
          name: forecastapp
          ports:
            - containerPort: 9090
